"""empty message

Revision ID: 0a1587d037a0
Revises: a180a7417fa9
Create Date: 2020-03-07 16:38:39.647678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a1587d037a0'
down_revision = 'a180a7417fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('latin_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latin_name')
    )
    op.drop_table('plants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('latin_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('common_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='plants_pkey'),
    sa.UniqueConstraint('latin_name', name='plants_latin_name_key')
    )
    op.drop_table('plant')
    # ### end Alembic commands ###
