"""empty message

Revision ID: 0ae8d80bf4d3
Revises: ac8f2dd5fd1e
Create Date: 2021-01-31 13:28:58.566286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae8d80bf4d3'
down_revision = 'ac8f2dd5fd1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement_unit', sa.Column('label', sa.String(), nullable=True))
    op.drop_column('measurement_unit', 'label_singular')
    op.drop_column('measurement_unit', 'label_plural')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement_unit', sa.Column('label_plural', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('measurement_unit', sa.Column('label_singular', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('measurement_unit', 'label')
    # ### end Alembic commands ###
