"""empty message

Revision ID: 0bc46ea6224b
Revises: d8a9f60d2425
Create Date: 2021-01-24 12:45:49.238549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc46ea6224b'
down_revision = 'd8a9f60d2425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement_unit', sa.Column('label_plural', sa.String(), nullable=True))
    op.add_column('measurement_unit', sa.Column('label_singular', sa.String(), nullable=True))
    op.drop_column('measurement_unit', 'label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement_unit', sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('measurement_unit', 'label_singular')
    op.drop_column('measurement_unit', 'label_plural')
    # ### end Alembic commands ###
