"""empty message

Revision ID: 1e689b8593d9
Revises: 9c6f1d0f81a1
Create Date: 2021-03-18 11:43:22.444650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e689b8593d9'
down_revision = '9c6f1d0f81a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('is_variety', sa.Boolean(), nullable=True))
    op.add_column('plant', sa.Column('variety_plant_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plant', 'plant', ['variety_plant_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plant', type_='foreignkey')
    op.drop_column('plant', 'variety_plant_fk')
    op.drop_column('plant', 'is_variety')
    # ### end Alembic commands ###
