"""empty message

Revision ID: 305856f5524f
Revises: 7e71357051eb
Create Date: 2020-05-12 07:30:01.996198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305856f5524f'
down_revision = '7e71357051eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_variety', sa.Column('lifespan_fk', sa.Integer(), nullable=True))
    op.add_column('plant_variety', sa.Column('soil_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plant_variety', 'lifespan', ['lifespan_fk'], ['id'])
    op.create_foreign_key(None, 'plant_variety', 'soil', ['soil_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plant_variety', type_='foreignkey')
    op.drop_constraint(None, 'plant_variety', type_='foreignkey')
    op.drop_column('plant_variety', 'soil_fk')
    op.drop_column('plant_variety', 'lifespan_fk')
    # ### end Alembic commands ###
