"""empty message

Revision ID: 42e955648e47
Revises: e138388d57e6
Create Date: 2021-01-25 12:05:32.850956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e955648e47'
down_revision = 'e138388d57e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_uri', sa.String(), nullable=True),
    sa.Column('frost_tolerant', sa.Boolean(), nullable=True),
    sa.Column('drought_tolerant', sa.Boolean(), nullable=True),
    sa.Column('soil_ph_low', sa.Integer(), nullable=True),
    sa.Column('soil_ph_high', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('plant_fk', sa.Integer(), nullable=True),
    sa.Column('category_fk', sa.Integer(), nullable=True),
    sa.Column('height_unit_fk', sa.Integer(), nullable=True),
    sa.Column('width_unit_fk', sa.Integer(), nullable=True),
    sa.Column('lifespan_fk', sa.Integer(), nullable=True),
    sa.Column('soil_fk', sa.Integer(), nullable=True),
    sa.Column('soil_fertility_fk', sa.Integer(), nullable=True),
    sa.Column('growth_habit_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_fk'], ['category.id'], ),
    sa.ForeignKeyConstraint(['growth_habit_fk'], ['growth_habit.id'], ),
    sa.ForeignKeyConstraint(['height_unit_fk'], ['measurement_unit.id'], ),
    sa.ForeignKeyConstraint(['lifespan_fk'], ['lifespan.id'], ),
    sa.ForeignKeyConstraint(['plant_fk'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['soil_fertility_fk'], ['soil_fertility.id'], ),
    sa.ForeignKeyConstraint(['soil_fk'], ['soil.id'], ),
    sa.ForeignKeyConstraint(['width_unit_fk'], ['measurement_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant_child_light_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('plant_child_fk', sa.Integer(), nullable=True),
    sa.Column('light_requirement_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['light_requirement_fk'], ['light_requirement.id'], ),
    sa.ForeignKeyConstraint(['plant_child_fk'], ['plant_child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_child_light_requirement')
    op.drop_table('plant_child')
    # ### end Alembic commands ###
