"""empty message

Revision ID: 505c5a7db7e8
Revises: fc6cdffe71a8
Create Date: 2020-03-07 19:18:22.041729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505c5a7db7e8'
down_revision = 'fc6cdffe71a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bed_plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('bed_fk', sa.Integer(), nullable=True),
    sa.Column('plant_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bed_fk'], ['bed.id'], ),
    sa.ForeignKeyConstraint(['plant_fk'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bed_plant')
    # ### end Alembic commands ###
