"""empty message

Revision ID: 5fb6096c429f
Revises: bae0f077d45c
Create Date: 2017-07-24 19:39:45.999517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb6096c429f'
down_revision = 'bae0f077d45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantcloningnotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('plant_cloning_fk', sa.Integer(), nullable=True),
    sa.Column('note_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plant_cloning_fk'], ['plantclonings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plantcloningnotes')
    # ### end Alembic commands ###
