"""empty message

Revision ID: 62c303d60ae6
Revises: c15201fefbc1
Create Date: 2017-06-21 15:03:23.587662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62c303d60ae6'
down_revision = 'c15201fefbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compostpilehistories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compost_pile_fk', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('moisture', sa.Integer(), nullable=True),
    sa.Column('turned', sa.Boolean(), nullable=True),
    sa.Column('scraps_added', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['compost_pile_fk'], ['compostpiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('compostpiles', sa.Column('finished', sa.DateTime(), nullable=True))
    op.add_column('compostpiles', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('compostpiles', sa.Column('label', sa.String(), nullable=True))
    op.add_column('compostpiles', sa.Column('started', sa.DateTime(), nullable=True))
    op.drop_column('compostpiles', 'date')
    op.drop_column('compostpiles', 'turned')
    op.drop_column('compostpiles', 'temperature')
    op.drop_column('compostpiles', 'scraps_added')
    op.drop_column('compostpiles', 'moisture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compostpiles', sa.Column('moisture', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('compostpiles', sa.Column('scraps_added', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('compostpiles', sa.Column('temperature', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('compostpiles', sa.Column('turned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('compostpiles', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('compostpiles', 'started')
    op.drop_column('compostpiles', 'label')
    op.drop_column('compostpiles', 'is_active')
    op.drop_column('compostpiles', 'finished')
    op.drop_table('compostpilehistories')
    # ### end Alembic commands ###
