"""empty message

Revision ID: 74ba324c02bb
Revises: 663639be58d3
Create Date: 2017-07-22 16:05:28.228173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ba324c02bb'
down_revision = '663639be58d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantgenerations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('total_seeds_obtained', sa.Integer(), nullable=True),
    sa.Column('date_seeds_obtained', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantlineagegenerations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('plant_lineage_fk', sa.Integer(), nullable=True),
    sa.Column('plant_generation_fk', sa.Integer(), nullable=True),
    sa.Column('plant_previous_generation_fk', sa.Integer(), nullable=True),
    sa.Column('is_origin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['plant_generation_fk'], ['plantgenerations.id'], ),
    sa.ForeignKeyConstraint(['plant_lineage_fk'], ['plantlineages.id'], ),
    sa.ForeignKeyConstraint(['plant_previous_generation_fk'], ['plantgenerations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plantlineagegenerations')
    op.drop_table('plantgenerations')
    # ### end Alembic commands ###
