"""empty message

Revision ID: 7e209076b8c4
Revises: acee35f59309
Create Date: 2020-03-07 13:04:51.097768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e209076b8c4'
down_revision = 'acee35f59309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'edible')
    op.drop_column('plants', 'image_small')
    op.drop_column('plants', 'image_large')
    op.drop_column('plants', 'medicinal')
    op.drop_column('plants', 'drought_tolerant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('drought_tolerant', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('medicinal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('image_large', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('image_small', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('plants', sa.Column('edible', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
