"""empty message

Revision ID: 99971a0e4318
Revises: 9e5d117a7780
Create Date: 2020-05-11 19:12:14.691621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99971a0e4318'
down_revision = '9e5d117a7780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('plant', sa.Column('soil_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plant', 'soil', ['soil_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plant', type_='foreignkey')
    op.drop_column('plant', 'soil_fk')
    op.drop_table('soil')
    # ### end Alembic commands ###
