"""empty message

Revision ID: 9c6f1d0f81a1
Revises: 1fdd9953c0bf
Create Date: 2021-03-18 08:47:23.670425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6f1d0f81a1'
down_revision = '1fdd9953c0bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plant_sub_species_key', 'plant', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('plant_sub_species_key', 'plant', ['sub_species'])
    # ### end Alembic commands ###
