"""empty message

Revision ID: 9e5d117a7780
Revises: ed0207c0a4d5
Create Date: 2020-05-11 18:46:57.281122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e5d117a7780'
down_revision = 'ed0207c0a4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_lifespan')
    op.add_column('plant', sa.Column('lifespan_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plant', 'lifespan', ['lifespan_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plant', type_='foreignkey')
    op.drop_column('plant', 'lifespan_fk')
    op.create_table('plant_lifespan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('plant_fk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lifespan_fk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lifespan_fk'], ['lifespan.id'], name='plant_lifespan_lifespan_fk_fkey'),
    sa.ForeignKeyConstraint(['plant_fk'], ['plant.id'], name='plant_lifespan_plant_fk_fkey'),
    sa.PrimaryKeyConstraint('id', name='plant_lifespan_pkey')
    )
    # ### end Alembic commands ###
