"""empty message

Revision ID: 9f59bd0c5d37
Revises: 61c9db884c97
Create Date: 2017-07-18 21:24:33.584117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f59bd0c5d37'
down_revision = '61c9db884c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantgenerations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_seeds_collected', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantingphysicalsources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantingsources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantharvests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_generation_fk', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('finish_date', sa.DateTime(), nullable=True),
    sa.Column('grams_harvested', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_generation_fk'], ['plantgenerations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_generation_fk', sa.Integer(), nullable=True),
    sa.Column('seeds_started', sa.Integer(), nullable=True),
    sa.Column('date_seeds_started', sa.DateTime(), nullable=True),
    sa.Column('starting_medium', sa.String(), nullable=True),
    sa.Column('seeds_sprouted', sa.Integer(), nullable=True),
    sa.Column('date_first_seeds_sprouted', sa.DateTime(), nullable=True),
    sa.Column('sprouts_planted', sa.Integer(), nullable=True),
    sa.Column('date_sprouts_planted', sa.DateTime(), nullable=True),
    sa.Column('plants_survived', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_generation_fk'], ['plantgenerations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantclones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_generation_fk', sa.Integer(), nullable=True),
    sa.Column('planting_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_generation_fk'], ['plantgenerations.id'], ),
    sa.ForeignKeyConstraint(['planting_fk'], ['plantings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantharvestnotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_harvest_fk', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('note_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plant_harvest_fk'], ['plantharvests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantlineages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_fk', sa.Integer(), nullable=True),
    sa.Column('plant_generation_fk', sa.Integer(), nullable=True),
    sa.Column('previous_plant_generation_fk', sa.Integer(), nullable=True),
    sa.Column('is_origin', sa.Boolean(), nullable=True),
    sa.Column('is_dead', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['plant_fk'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['plant_generation_fk'], ['plantgenerations.id'], ),
    sa.ForeignKeyConstraint(['previous_plant_generation_fk'], ['plantgenerations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantclonings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_clone_fk', sa.Integer(), nullable=True),
    sa.Column('date_cloned', sa.DateTime(), nullable=True),
    sa.Column('amount_cloned', sa.Integer(), nullable=True),
    sa.Column('amount_rooted', sa.Integer(), nullable=True),
    sa.Column('amount_planted', sa.Integer(), nullable=True),
    sa.Column('root_hormone_used', sa.Boolean(), nullable=True),
    sa.Column('rooting_medium', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plant_clone_fk'], ['plantclones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plantclonings')
    op.drop_table('plantlineages')
    op.drop_table('plantharvestnotes')
    op.drop_table('plantclones')
    op.drop_table('plantings')
    op.drop_table('plantharvests')
    op.drop_table('plantingsources')
    op.drop_table('plantingphysicalsources')
    op.drop_table('plantgenerations')
    # ### end Alembic commands ###
