"""empty message

Revision ID: ab73a540d0a5
Revises: dd0e603581fa
Create Date: 2021-01-24 11:36:36.135513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab73a540d0a5'
down_revision = 'dd0e603581fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('genus_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'species', 'genus', ['genus_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'species', type_='foreignkey')
    op.drop_column('species', 'genus_fk')
    # ### end Alembic commands ###
