"""empty message

Revision ID: b0507ded3c50
Revises: 62c303d60ae6
Create Date: 2017-06-21 16:49:00.202026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0507ded3c50'
down_revision = '62c303d60ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rainfalltotals', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rainfalltotals', 'name')
    # ### end Alembic commands ###
