"""empty message

Revision ID: b37b52e28c4f
Revises: 0bc46ea6224b
Create Date: 2021-01-24 13:46:02.063153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37b52e28c4f'
down_revision = '0bc46ea6224b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_propagation', sa.Column('propagation', sa.Text(), nullable=True))
    op.drop_constraint('plant_propagation_propagation_fk_fkey', 'plant_propagation', type_='foreignkey')
    op.drop_column('plant_propagation', 'propagation_fk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_propagation', sa.Column('propagation_fk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('plant_propagation_propagation_fk_fkey', 'plant_propagation', 'propagation', ['propagation_fk'], ['id'])
    op.drop_column('plant_propagation', 'propagation')
    # ### end Alembic commands ###
