"""empty message

Revision ID: b8f8de0c1f59
Revises: 5b5901636687
Create Date: 2017-07-24 20:45:40.860939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f8de0c1f59'
down_revision = '5b5901636687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantharvestnotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_harvest_fk', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('note_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plant_harvest_fk'], ['plantharvests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plantharvestnotes')
    # ### end Alembic commands ###
