"""empty message

Revision ID: b94288a31966
Revises: 8c3b5b99e9a9
Create Date: 2021-03-23 14:29:48.236054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94288a31966'
down_revision = '8c3b5b99e9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('drought_tolerant', sa.Integer(), nullable=True))
    op.add_column('plant', sa.Column('frost_tolerant', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'frost_tolerant')
    op.drop_column('plant', 'drought_tolerant')
    # ### end Alembic commands ###
