"""empty message

Revision ID: bae0f077d45c
Revises: aa64a63f78c8
Create Date: 2017-07-24 19:19:55.648873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae0f077d45c'
down_revision = 'aa64a63f78c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantclonings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('plant_generation_fk', sa.Integer(), nullable=True),
    sa.Column('planting_physical_source_fk', sa.Integer(), nullable=True),
    sa.Column('date_cloned', sa.DateTime(), nullable=True),
    sa.Column('number_cloned', sa.Integer(), nullable=True),
    sa.Column('number_rooted', sa.Integer(), nullable=True),
    sa.Column('date_first_plant_rooted', sa.Date(), nullable=True),
    sa.Column('clones_planted', sa.Integer(), nullable=True),
    sa.Column('date_clones_planted', sa.Date(), nullable=True),
    sa.Column('clones_survived', sa.Integer(), nullable=True),
    sa.Column('date_next_generation_seeds_collected', sa.DateTime(), nullable=True),
    sa.Column('root_hormone_used', sa.Boolean(), nullable=True),
    sa.Column('root_hormone_type', sa.String(), nullable=True),
    sa.Column('rooting_medium', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plant_generation_fk'], ['plantgenerations.id'], ),
    sa.ForeignKeyConstraint(['planting_physical_source_fk'], ['plantingphysicalsources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plantclonings')
    # ### end Alembic commands ###
