"""empty message

Revision ID: c15201fefbc1
Revises: d93f307aa6a9
Create Date: 2017-06-21 08:24:49.196387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15201fefbc1'
down_revision = 'd93f307aa6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compostpiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('moisture', sa.Integer(), nullable=True),
    sa.Column('turned', sa.Boolean(), nullable=True),
    sa.Column('scraps_added', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compostpiles')
    # ### end Alembic commands ###
