"""empty message

Revision ID: c46a23ad0504
Revises: 95f4711ff324
Create Date: 2021-03-23 14:09:20.739198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46a23ad0504'
down_revision = '95f4711ff324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'drought_tolerant')
    op.drop_column('plant', 'frost_tolerant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('frost_tolerant', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('plant', sa.Column('drought_tolerant', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
