"""empty message

Revision ID: c786c10b95a4
Revises: e644a43a0589
Create Date: 2021-01-24 11:11:19.835932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c786c10b95a4'
down_revision = 'e644a43a0589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plant_family_fk_fkey', 'plant', type_='foreignkey')
    op.drop_column('plant', 'family_fk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('family_fk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('plant_family_fk_fkey', 'plant', 'family', ['family_fk'], ['id'])
    # ### end Alembic commands ###
