"""empty message

Revision ID: d8a9f60d2425
Revises: 39a40758d10d
Create Date: 2021-01-24 12:23:12.053604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a9f60d2425'
down_revision = '39a40758d10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plant_genus_fk_fkey', 'plant', type_='foreignkey')
    op.drop_column('plant', 'genus_fk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('genus_fk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('plant_genus_fk_fkey', 'plant', 'genus', ['genus_fk'], ['id'])
    # ### end Alembic commands ###
