"""empty message

Revision ID: dd0e603581fa
Revises: c786c10b95a4
Create Date: 2021-01-24 11:14:38.420014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0e603581fa'
down_revision = 'c786c10b95a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genus', sa.Column('family_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'genus', 'family', ['family_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genus', type_='foreignkey')
    op.drop_column('genus', 'family_fk')
    # ### end Alembic commands ###
