"""empty message

Revision ID: e138388d57e6
Revises: f0ff7743bdb0
Create Date: 2021-01-25 09:05:00.880069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e138388d57e6'
down_revision = 'f0ff7743bdb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('use', sa.Column('text', sa.Text(), nullable=True))
    op.drop_column('use', 'label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('use', sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('use', 'text')
    # ### end Alembic commands ###
