"""empty message

Revision ID: e644a43a0589
Revises: 550b52494d81
Create Date: 2021-01-23 15:55:12.939458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e644a43a0589'
down_revision = '550b52494d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_propagation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('plant_fk', sa.Integer(), nullable=True),
    sa.Column('propagation_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_fk'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['propagation_fk'], ['propagation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('plant', sa.Column('soil_ph_high', sa.Integer(), nullable=True))
    op.add_column('plant', sa.Column('soil_ph_low', sa.Integer(), nullable=True))
    op.drop_constraint('plant_propagation_fk_fkey', 'plant', type_='foreignkey')
    op.drop_column('plant', 'soil_ph')
    op.drop_column('plant', 'propagation_fk')
    op.drop_constraint('plant_water_requirement_water_requirement_fk_fkey', 'plant_water_requirement', type_='foreignkey')
    op.create_foreign_key(None, 'plant_water_requirement', 'water_requirement', ['water_requirement_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plant_water_requirement', type_='foreignkey')
    op.create_foreign_key('plant_water_requirement_water_requirement_fk_fkey', 'plant_water_requirement', 'plant_water_requirement', ['water_requirement_fk'], ['id'])
    op.add_column('plant', sa.Column('propagation_fk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plant', sa.Column('soil_ph', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('plant_propagation_fk_fkey', 'plant', 'propagation', ['propagation_fk'], ['id'])
    op.drop_column('plant', 'soil_ph_low')
    op.drop_column('plant', 'soil_ph_high')
    op.drop_table('plant_propagation')
    # ### end Alembic commands ###
