"""empty message

Revision ID: fc6cdffe71a8
Revises: 65a67aa13399
Create Date: 2020-03-07 18:54:31.719899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6cdffe71a8'
down_revision = '65a67aa13399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_bed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('garden_fk', sa.Integer(), nullable=True),
    sa.Column('bed_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bed_fk'], ['bed.id'], ),
    sa.ForeignKeyConstraint(['garden_fk'], ['garden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('garden_bed')
    op.drop_table('garden')
    # ### end Alembic commands ###
